src/embree.cpp
This PR adds support to double precision I/O to the `jitc_embree_trace` API. This is used in the parent `Mitsuba` project for enabling double precision ray tracing using the native KD-tree.
=> Add double precision support to jitc_embree_trace

src/optix_api.cpp
When running mitsuba3 for **cuda_rgb** I got the following error:
```
robin@ray:~/src/mitsuba3$ ./build/mitsuba -t 1 -m cuda_rgb resources/data/scenes/cbox/cbox-rgb.xml   -o test
2022-08-15 11:03:31 INFO  main  [mitsuba.cpp:341] Mitsuba version 3.0.1 (robin/upgrade-mitsuba3[64e8b42a], Linux, 64bit, 1 thread, 8-wide SIMD)
2022-08-15 11:03:31 INFO  main  [mitsuba.cpp:342] Copyright 2022, Realistic Graphics Lab, EPFL
2022-08-15 11:03:31 INFO  main  [mitsuba.cpp:343] Enabled processor features: cuda llvm avx2 avx fma f16c sse4.2 x86_64
2022-08-15 11:03:31 INFO  main  [xml.cpp:1393] Loading XML file "resources/data/scenes/cbox/cbox-rgb.xml" with variant "cuda_rgb"..
2022-08-15 11:03:31 INFO  main  [xml.cpp:668] Loading included XML file "resources/data/scenes/cbox/fragments/base.xml" .. …
```
=> Fix unreported cause of optix_initialize failure

include/drjit-core/optix.h, src/api.cpp, src/eval.cpp, src/eval_cuda.cpp, src/init.cpp, src/internal.h, src/optix_api.cpp, src/optix_api.h, tests/triangle.cpp
This PR addresses long standing issues with the management of Optix pipelines and SBT in Dr.Jit:
- OptiX pipeline and SBT lifetime was left to the caller's responsability, although it couldn't be aware of pending raytracing operations in un-evaluated kernels.
- OptiX pipeline and SBT was configured per thread, stored in the `ThreadState`, making it impossible to evaluate a kernel containing ray tracing operations traced in another thread.
- `jit_optix_configure()` had to be called before every call to `jit_optix_ray_trace()` to copy the pipeline and SBT data. This caused unecessary `memcpy` and didn't work reliably when multiple pipelines and SBT would be used simultaneously on the same thread.
This patch associated an Optix pipeline and an Optix SBT to every ray tracing operation. To …
=> Optix pipeline and SBT management refactoring

src/vcall.cpp
This is a fix for mitsuba-renderer/mitsuba3#356.
When a loop gets recorded and some of the dependent input/output variables are optimized out, the respective `indices` referenced in `Extra::dep` get replaced by `0` entries in [`jitc_var_loop()`](https://github.com/tomix1024/drjit-core/blob/044f04b54fce4af81fd841352fed594889e6b608/src/loop.cpp#L210).
When this loop is then part of a `jitc_var_vcall_collect_data()` traversal, a variable with an id (`index`) of `0` is referenced that does not exist and an exception is raised.
A simple check if the index of the dependent variable is zero before calling `jitc_var_vcall_collect_data()` recursively fixes the problem.
=> Fix jit_var(r0): unknown variable when recording virtual calls

include/drjit-core/jit.h, include/drjit-core/optix.h, src/api.cpp, src/eval_llvm.cpp, src/llvm_api.h, src/optix_api.cpp, src/optix_api.h, src/printf.cpp, src/vcall.cpp
This PR attempts to fix raytracing operation in virtual function calls and add the ability to ray trace multiple scenes within a single OptiX megakernel. This implies that those scenes share the same SBT, which requires the implementation of `jit_optix_update_sbt()`. 
This PR also disables the OptiX validation mode by default as it isn't reliable in current OptiX versions.
=> Fix raytracing operation in virtual function calls

src/var.cpp
On the LLVM backend, a special variable ("default mask") disables memory operations on some SIMD lanes when the wavefronts isn't an exact multiple of the platform's vectorization width.
A pathological issue that Ziyi ran into is that that mask variable can be evaluated and stored in memory. That's not good because the contents of this (scalar) variable depend on the evaluation context.
There are two possible ways of fixing this issue:
1. Construct the mask variable so that it has the necessary size. I first tried to go this route, but it's tricky. In some places we create the mask but don't yet know what the eventual wavefront size will be.
2. Ignore calls to jit_var_[schedule, eval](default masks). Raise an error message when calling jit_var_ptr(default mask).
This commit implements …
=> Do not evaluate the default mask on LLVM

include/drjit-core/jit.h, src/api.cpp, src/init.cpp, src/internal.h
This PR adds helpers to switch CUDA contexts.
For OptiX, we expose a `OptixDeviceContext` throught `jit_optix_context()`. This context depends on a CUDA context and if users want to re-use it for other OptiX computations outside of Dr.Jit they cannot do it without setting the same CUDA context.
These new helpers will allow users to do exactly this or, more generally, scope any other CUDA computations they might want to do without Dr.Jit.
=> Expose new functions to manually push/pop CUDA contexts

src/eval_cuda.cpp, src/eval_llvm.cpp, src/op.cpp, src/var.cpp, src/vcall.cpp, tests/CMakeLists.txt, tests/basics.cpp, tests/vcall.cpp
Here is my 3rd attempt at implementing the handling of external literal in recorded virtual function calls.
The previous patch wasn't optimal as it would prevent the constant propagation of literal arguments through virtual function calls. While de-virtualization was working properly, it still meant that large data-structure arguments with a lot of zero-members would generate a lot of un-necessary "opaque" IR that would turn out to yield zeros.
This is especially important for automatic differentiation when only a subset of the input arguments will have non-zero gradients.
Looking back at the original purpose of those changes, we are only interested in "un-baking"  literal variables created before tracing the VCalls that are directly accessible within the functions (e.g. plugin …
=> Auto opaque vcall  - 3rd attempt

include/drjit-core/texture.h, src/api.cpp, src/cuda_tex.cpp, src/cuda_tex.h
The functions `jit_cuda_tex_lookup` and `jitc_cuda_tex_bilerp_fetch` would previously take a mask as an argument which was used to fill the result with zeros at the masked indices. This PR removes the `mask` arguments entirely.
The output variables for both functions are always new JIT variables, users can still zero-out certain indices if they need to with a second operation. Additionally, because there is always a wrapping feature on a texture, there will never be invalid lookup coordinates (NaNs and infinites are supported too).
Masking at this level was therefore unnecessary.
=> Remove masking from hardware texture operations

include/drjit-core/jit.h, include/drjit-core/state.h, src/api.cpp, src/eval_llvm.cpp, src/op.cpp, src/optix_api.cpp, src/printf.cpp, src/var.cpp, src/var.h, src/vcall.cpp, tests/ekloop.h, tests/vcall.cpp
This commit bundles several improvements to the mask stack. For context, the mask stack is an implicit stack of masks, whose top element is automatically applied to memory reads/writes and a few other operations to disable inactive entries of the current wavefront. That is important because undefined behavior resulting from unmasked memory operations could cause inconsistencies or even crash the program.
LLVM has an implicit default mask (even when the stack is empty) that is needed because the wavefront size might not be an exact multiple of the SIMD vector width. This means that some elements are always masked even in the absence of conditional operations that normally cause some masking (loops, vcalls).
The changes are:
- The implicit default mask on LLVM is now consistently created …
=> Mask stack improvements

src/eval_cuda.cpp, src/optix_api.cpp
Mitsuba rendering tasks executed using Dr.Jit's OptiX backend are currently limited to 2^30 ≈ 1 billion Monte Carlo samples in total, which sounds like a lot. However, that's just enough to render a full HD image using 512 samples per pixel:
1920*1080*512 = 1'061'683'200 < 1'073'741'824 = 2^32
This commit increases the limit to 4 billion, which corresponds to 2048 samples per pixel at 1080p resolution. This is the *absolute maximum* wavefront size that Dr.Jit can accommodate due to its 32 bit based indexing.
It's worth mentioning that further increasing that limit by upgrading to 64 bit indexing is not a good idea as this comes with significant costs on modern GPUs that lack 64 bit registers. Instead, multiple rendering passes should be used in the renderer to handle such very large …
=> Support large launches with up to 2^32 threads on OptiX backend

src/eval.cpp, src/eval_cuda.cpp, src/eval_llvm.cpp, src/op.cpp
This patch gets rid of the use of `@pXXX ...` predicated instructions in the PTX generation for `dr.gather`, `dr.scatter` and `dr.select()`.
=> Remove PTX `@p` predicates

README.md, include/drjit-core/array.h, include/drjit-core/containers.h, include/drjit-core/jit.h, include/drjit-core/state.h, src/api.cpp, src/common.h, src/cuda_tex.cpp, src/eval.cpp, src/eval_llvm.cpp, src/init.cpp, src/internal.h, src/loop.cpp, src/op.cpp, src/optix_api.cpp, src/printf.cpp, src/var.cpp, src/var.h, src/vcall.cpp, tests/basics.cpp, tests/ekloop.h, tests/vcall.cpp
The Variable data structure currently keeps track of an internal and an external reference count. We aren't really using that property, and it consumes precious storage in an otherwise highly optimized data structure. This experimental commit merges them into a joint 32 bit reference count field to free up memory for subsequent refactoring.
=> Merged internal and external reference count fields

include/drjit-core/jit.h, include/drjit-core/state.h, src/api.cpp, src/eval.cpp, src/eval.h, src/eval_cuda.cpp, src/eval_llvm.cpp, src/init.cpp, src/internal.h, src/loop.cpp, src/op.cpp, src/optix_api.cpp, src/printf.cpp, src/var.cpp, src/var.h, src/vcall.cpp, tests/basics.cpp, tests/mem.cpp
This commit builds on PR #38 and further refactors the `Variable` data structure by adding a ``kind`` field that specifies the kind of the variable in question. The field must be set to one of:
- `VarKind::Literal`: constant literals
- `VarKind::Stmt`: a statement in an intermediate representation (LLVM IR, PTX)
- `VarKind::Data`: a pointer to device memory
This permits overlapping `data`, `literal`, and `stmt` using a union, which frees up 64 bits (`data` was previously stored separately):
```cpp
union {
uint64_t literal;
const char *stmt;
void *data;
}
```
The `Variable` struct was extended with convenience functions to check `kind`:
```cpp
inline bool is_literal() { return kind == (uint32_t) VarKind::Literal; }
inline bool is_stmt()    { return kind == (uint32_t) VarKind::Stmt; } …
```
=> Further variable data structure refactoring

src/init.cpp, src/internal.h, src/op.cpp
This PR consists of two changes:
The first improves the implementation of the important special case of FP32 scatter-add reduction on CUDA/OptiX. The previous implementation generated up to 32 atomic memory transaction per warp, causing significant contention in some cases. The new implementation first performs an intra-warp reduction. A warp that consistently targets the same location in memory will then only generate a single memory transaction.
The second adjusts the type of PTX IR generated by Dr.Jit. We previously targeted a generic low PTX version and compute capability. The commit changes the logic so that both numbers are bumped according to a table containing known safe combinations.
=> Improve efficiency of CUDA scatter-reduction

src/eval_cuda.cpp, src/optix_api.cpp
The following 2 commits of this PR do:
1) A bug fix related to an issue reported here: https://github.com/mitsuba-renderer/mitsuba3/issues/408. During `jit_assemble_cuda` JIT variables can change addresses because of extra assembly steps required by some variables (a vcall variable in this specific instance). 
2) Improvements to the logging when the OptiX compilation fails. The new message prints the exact failure reported by OptiX rather than only the compilation state.
=> Bug fix for CUDA assembly & logging improvements for OptiX compilation (minor changes)

include/drjit-core/state.h, src/api.cpp, src/eval.cpp, src/eval.h, src/eval_llvm.cpp, src/loop.cpp, src/var.cpp, src/var.h, src/vcall.cpp, tests/ekloop.h, tests/vcall.cpp
Note: this PR builds on PR #40.
When Dr.Jit generates IR output, there is a question of how statements should be ordered. Any ordering that does not violate variable dependencies or basic block boundaries is in principle admissible. Previously, Dr.Jit arranged variables in the order in which they were originally constructed by sorting them according to the monotonically increasing variable index.
This was correct but had three negative implications:
- Variable IDs are 32 bit counters in Dr.Jit, and this is generally desirable to keep the central `Variable` data structure small. However, long-running programs could overflow that 32 bit counter, which meant that the program order no longer made sense. Dr.Jit failed with an error when this happened. At this point, a number of users have …
=> Make program structure independent of variable indices

include/drjit-core/jit.h, src/vcall.cpp
This PR adapt `jit_var_vcall_reduce` to also work with callable that are not methods of classes registered in the Dr.Jit registry. This is necessary for the implementation of `dr.switch` and `dr.dispatch()`.
=> Fix jitc_var_vcall_reduce for dr.switch()

src/eval.cpp
This PR fixes a bug where `jitc_eval`  would crash when a variable is evaluated and used in two kernels of different sizes.
Here's a snippet that illustrates when this could occur:
```python
import drjit as dr
from drjit.cuda import Float
a = dr.opaque(Float, 1)
b = Float([1, 2, 3])
c = a + 1 # c has size 1
d = b + c # d has size 3
dr.eval(d, c) # Two kernel launches (size 3 and 1)
print(c) # Crash here
```
During `dr.eval(d, c)`  both kernels execute as expected, and the scheduled variables for `c` and `d`  have the correct pointers to device memory. However, there is also an internal duplicate `c` of size 3 which is need to evaluate `d`.
When writing the device pointers back to the actual JIT variables the current code would sometimes (depending or kernel launch order) use the …
=> Bug: Evaluating variable in two kernels of different sizes

src/cuda_api.cpp, src/init.cpp, src/internal.h, src/printf.cpp, src/registry.cpp, src/util.cpp, src/vcall.cpp
This patch fixes a concurrency issue with asynchronous calls to `jitc_free` in `vcall.cpp` and `util.cpp`. 
Here is an example of the potential sequence of events that might lead to a crash:
```
Thread #1: jitc_free(123)
-> state.alloc_free.push_back(123);  
Thread #2: jitc_malloc()
-> state.alloc_free.find(...); -> 123
-> state.alloc_used.push_back(123); -> does nothing since 123 is already in this set
Thread #1: 
-> state.alloc_used.erase(123); <- also remove the one that was just added by thread #2
Thread #2: jitc_free(123) -> CRASH since it cannot find 123 in alloc_used as it was erased by thread #1
```
This can be fixed by replacing those two calls to `jitc_free` with `jit_free`.
=> Fix asynchronous jit_free calls (and more)

src/llvm_eval.cpp, src/op.cpp, tests/mem.cpp
This PR implements the missing logic for `VarKind::ScatterKahan` in LLVM mode.
(Run for CI)
=> Implement Kahan-style scatter-accumulation for LLVM

src/vcall.cpp, tests/vcall.cpp
This PR changes the behavior of the `VCallOptimize` flag.
Currently, when the `VCallOptimize` flag is set, virtual function return values that are identical across all instances/targets are de-virtualized (the computation is inlined into the caller's scope). This PR limits the de-virtualization to return values that are literals, reducing some potentially aggressive inlining.
There are no apparent performance changes in standard scenes:
```
| scene          | mode   | compilation before   | compilation after   | execution before   | execution after   |
|----------------|--------|----------------------|---------------------|--------------------|-------------------|
| glass-of-water | cuda   | 4.76 (1.00)          | 4.77 (1.00)         | 4.58  (1.00)       | 4.58  (1.00)      |
| …
```
=> Virtual function calls should only devirtualize literals

src/io.cpp, src/llvm_core.cpp, src/loop.cpp, src/op.cpp, src/strbuf.cpp, src/strbuf.h, src/vcall.cpp, tests/basics.cpp
This PR fixes a few smaller undefined behaviors (see also the discussion in #54).
The fixes in this PR so far are very minor: 
- it ensures that StringBuffers always have a capacity of >= 1. This fixes undefined behavior related to pointer arithmetic on null pointers (addresses #53)
- it fixes an undefined behavior due to invoking memcpy with a nullptr by first checking if >0 bytes should be copied. Calling memcpy(..., nullptr, 0) is invalid, even though logically this should be fine. 
- it fixes a small memory leak of an LLVM error string
There are a few more issues that we we could address also in this PR:
- In test_basics, we are testing the result of CTZ and SHL operations using negative numbers. Left-shifting negative numbers is undefined behavior. Maybe these ops should be skipped …
=> Various fixes of undefined behavior

src/llvm_eval.cpp
Hi,
I came across a strange bug in Mitsuba this week. Somehow during optimization, at a seemingly arbitrary (but not random) iteration, the LLVM backend would emit an error
```
drjit_f04142c9302e9174a3dbe2f6a84e85d3:1755:23: error: use of undefined value '%f0'
store <8 x float> %f0, ptr %f0_p5, align 32, !noalias !2, !nontemporal !3
^
```
Weirdly enough, this happened without any particular change of the code. The kernel was identical for all iterations of the optimization, except for this one extra line. And depending on the code in my program, it would happen at different iterations or not at all. But it was not random - for a fixed code, it would happen exactly at the same point across machines.
The variable it was trying to store here came from a VCall's creation, which didn't make …
=> Fix bug due to iterator invalidation

src/llvm_core.cpp
This PR is a follow-up to #59.
When the FMA3 instruction set is not supported on the target CPU, the JIT will now gracefully shutdown with a warning message.
Correctly emulating the instruction is difficult and bumping the CPU architecture requirement is too-strict as some users might only use the CUDA backend.
(Fixes https://github.com/mitsuba-renderer/drjit/issues/46).
=> Disable LLVM backend when the FMA3 instruction set is unavailable

src/eval.cpp, tests/loop.cpp
Evaluation of side-effects was explicitly disabled whenever Dr.Jit was in a recorded phase of some computation. This PR changes this behaviour and now allows these evaluations.
The new test case in this PR motivates this change: we want to access/use some "dirty" variable during a recorded loop.
The original behavior was introduced in https://github.com/mitsuba-renderer/drjit-core/commit/30b3f575004ed83aa778c845d35cfdd3c49af88a. At that point in the development of Dr.Jit, symbolic loops or virtual function calls did not store their side-effects in a separate list (`ThreadState.side_effects_recorded` did not exist yet). The fact that these are now stored in a separate list allows us to disambiguate which side-effects are independent of the recording and can be evaluated.
=> Allow evaluations of side effects during recording

CMakeLists.txt, src/optix_core.cpp
Add support to optionally enable debug and validation flags in OptiX
=> Add OptiX debug/validation level as CMake options

src/init.cpp
This commit fixed a typo in the name of the `nvidia-smi` utility, a term which users may elect to copy and run in their terminal during troubleshooting.
There are no other language or functionality changes in this PR.
=> Fix a typo in the name of `nvidia-smi` utility.

src/cuda_eval.cpp, src/llvm_eval.cpp
Identified using the reproducer script below, with `MI_SANITIZE_ADDRESS` enabled, defining `DRJIT_VALGRIND=1` in `var.cpp`, and running under AddressSanitizer.
The full command was:
```
LD_PRELOAD="$(pwd)/../resources/dlopen_interceptor.so:$(clang++-15 -print-file-name=libclang_rt.asan-x86_64.so)" ASAN_OPTIONS="protect_shadow_gap=0,verify_asan_link_order=0,detect_stack_use_after_return=1,detect_leaks=1" DRJIT_NO_RTLD_DEEPBIND=1 CUDA_VISIBLE_DEVICES=0 CUDA_LAUNCH_BLOCKING=1 python3.11 -u ../src/render/tests/test_segfault_optix.py > log.txt 2>&1
```
where `dlopen_interceptor.so` is a short library that removes `RTLD_DEEPBIND` flags from any `dlopen` call. Code by [zhi_xz](https://forums.developer.nvidia.com/u/zhi_xz) ([source](https://forums.developer.nvidia.com/t/cupti-profiling-api-memory- …
=> Fix read-after-free in `jitc_cuda_assemble`

src/cuda.h, src/cuda_core.cpp, src/init.cpp
A race condition was introduced in 12a2b8b: `jit_init` calls `jitc_cuda_compile`, which now locally unlocks the state lock. This means that operations such as `jitc_init_thread_state` could start executing before `jit_init` would complete.
The race condition was easily reproducible on my machine by deleting the cache directories. The next run would almost always trigger:
```
jit_init_thread_state(): the CUDA backend is inactive because it has not been initialized via jit_init(), or because the CUDA driver library ("libcuda.so") could not be found! Set the DRJIT_LIBCUDA_PATH environment variable to specify its path.
```
As a simple fix, I introduced a `release_state_lock` argument, which is only set to `false` in `jit_init`. Hopefully that's the only case where we really need to keep the …
=> Fix race condition in `jit_init`

include/drjit-core/nanostl.h
Pointer to const types did not have a specialization for an appropriate `formatter`. 
:warning: This requires an include of `type_traits` in the `nanostl.h` file. (Technically, we were already using `std::is_pointer_v` which is defined in `type_traits`, so I'm guessing `utility` already partially covers `type_traits`.)
=> Formatter for pointer to const types

src/common.h
Fixes an error when compiling with GCC 13.
Build log:
https://gist.github.com/ConnorBaker/4fa0dd6e8b6ca71cbe60c1983b97e2ab
Snippet
```console
/nix/store/ldxpb0mc2qxx247wi5bnsplcaxdnhyw5-gcc-wrapper-13.2.0/bin/g++ -DDRJIT_BUILD=1 -DDRJIT_DYNAMIC_CUDA=1 -DDRJIT_DYNAMIC_LLVM=1 -DDRJIT_ENABLE_OPTIX=1 -DLZ4LIB_VISIBILITY="" -DXXH_EXPORT -Ddrjit_core_EXPORTS -I/build/source/include -fdiagnostics-color=always -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -fPIC -fvisibility=hidden -march=native -Wall -Wextra -Wno-unused-local-typedefs -fno-math-errno -ffp-contract=fast -fno-trapping-math -Wno-free-nonheap-object -MD -MT CMakeFiles/drjit-core.dir/src/strbuf.cpp.o -MF CMakeFiles/drjit-core.dir/src/strbuf.cpp.o.d -o CMakeFiles/drjit-core.dir/src/strbuf.cpp.o -c /build/source/src/strbuf.cpp
In file …
```
=> src/common.h: explicitly include `cstdint`

src/cuda_ts.cpp, src/cuda_ts.h, src/eval.cpp, src/eval.h, src/internal.h, src/llvm_ts.cpp, src/llvm_ts.h
Adds a new virtual function to `ThreadState`, that takes a `Kernel` after and launches it.
This modularizes part of `jitc_run`.
=> jitc_run modularization

include/drjit-core/jit.h, src/api.cpp, src/registry.cpp, src/registry.h
This PR adds an Interface to get an arbitrary pointer to an instance in a given domain: `jit_registry_peek`. This is useful for vectorized dispatches where it is sometimes necessary to trace some function for an arbitrary instance.
The proposed implementation is effectively a compostion of `jit_registry_ptr` and `jit_registry_id_bound`. Returning the highest ID in a domain isn't a particularly desirable property for this function, but it is the only way (I believe) to return a valid pointer in O(1) without making any additional changes to the registry data structures.
=> Add `jit_registry_peek`

src/call.cpp, src/var.cpp
This PR introduces two fixes:
* 0419185c67427dcbc2dc4232ec8e8c6e61eacd8f is a fix for yet another case where we might have used an invalidated `Variable*`
* 4623c62d4e2e7b75d7aecaaa016d7211ec7e92be is a fix for vectorized calls, where we previously might not have completely filled their data map if a callable contained a loop.
=> Fixes to `jitc_var_reduce_dot` and `jitc_var_call_analyze`

src/var.cpp
When the result of `jit_var_migrate` is a new (evaluated) variable, we don't want to copy over the dependencies of the source variable.
It looks to me like they were copied accidentally, since the ref count of the dependencies was not increased.
This issue came up when doing:
```py
a = mi.Float([1, 2, 3])
b = dr.reshape(mi.Float, a, 2, shrink=True)
c = b.numpy()
```
When `c` gets de-allocated, it tried to decrease the dependencies of `b`, which have already been freed.
=> jit_var_migrate: don't copy dependencies of source variable

src/llvm_eval.cpp
This PR introduces a small fix to LLVM symbolic loops. 
When a loop's state is partially evaluated and then re-used in some other evaluation, it could produce illegal LLVM IR.
Here's an example:
```python
import drjit as dr
m = dr.llvm
@dr.syntax
def func():
idx = dr.zeros(m.UInt32)
val = dr.zeros(m.UInt32)
while dr.hint(idx < 3, mode='symbolic'):
idx += 1
val += 2 + idx
return idx, val
idx, val = func()
print('size: ', idx)
print('sum: ', val + idx)
```
(I will add this as a test case to Dr.Jit.)
During assembly, we incorrectly assume that loop outputs are still of kind `LoopOutput` which are never assembled explicitly. In reality, loop outputs could have been evaluated and hence would be assembled to a `load` statement leading to a duplicate definition of a register name.
=> Fix LLVM symbolic loops with evaluated outputs

src/llvm_eval.cpp
Tiny fix for half-precision floating point vectors that seems to affect all releases of LLVM.
All "passing" CI runs were just relying on UB, but should/could have been crashing. The current LLVM 18 build on `master` fails, where as this PR passes.
More details (and maybe an upcoming fix) are tracked here in the LLVM project: https://github.com/llvm/llvm-project/issues/102611
=> Fix for loading fp16 vectors in LLVM

src/cuda_eval.cpp, src/llvm_eval.cpp, src/loop.cpp
This PR fixes a bug when assembling local memory operations inside of a symbolic loop. In particular, it would not assemble operations that could modify the local memory variable. 
Here's an example:
```python
import drjit as dr
from drjit.cuda import UInt32
@dr.syntax()
def func():
local = dr.alloc_local(UInt32, size=8, value=UInt32(0))
size = UInt32(0)
val = UInt32(0)
while size < 5:
val += local[size]
size += 1
local[size] = UInt32(4) # Never gets assembled
print(val) # Prints '0' currently, should be 16
func()
```
(Will be added as a Dr.Jit test case)
Currently, the write operation at the end of the loop is not traversed during `jitc_var_traverse()`.
Typically, when a loop input variable (`kind == VarKind::LoopPhi`) is traversed, we also traverse its corresponding loop output variable …
=> Fix assembly of local memory uses in symbolic loops

include/drjit-core/jit.h, src/api.cpp, src/call.cpp, src/call.h, src/cuda_ts.cpp, src/cuda_ts.h, src/eval.cpp, src/internal.h, src/llvm_ts.cpp, src/llvm_ts.h, src/malloc.cpp, src/op.cpp, src/var.cpp
This PR makes the following changes in order to prepare for frozen functions.
- A `KernelFreezing` and `FreezingScope` flags, and associated tests
- A `jit_var_is_unaligned` function, querying if a variable is unaligned
- Adds kernel_param_ids, kernel hash and kernel key to the `ThreadState::launch` funciton interface
- Moves the code, passing kernel params through global memory on CUDA to the `CudaThreadState`
- Adds a `barrier` function and implements it for `LLVM` that simplifies managing concurrency between `LLVM` kernels
- Adds a `notify_free` function to the ThreadState
- Removes the use of `cuMemcpyAsync` in `jitc_var_mem_copy`
=> Frozen ThreadState prep

include/drjit-core/array.h, include/drjit-core/jit.h, src/api.cpp, tests/array.cpp, tests/basics.cpp, tests/loop.cpp, tests/vcall.cpp
This commit changes the signature of ``jit_var_inc_ref(uint32_t index)`` to return the input ``index``. This is of course redundant, but it shortens simultaneous assignments + refcounting operations:
```
variable = jit_var_inc_ref(index);
```
This is an improvement to the current pattern
```
variable = index;
jit_var_inc_ref(index);
```
which is found quite often. The change also makes AD and JIT-level reference counting more similar to each other.
Finally, there is also a small potential code generation improvement since the compiler does not have to stash the index on the stack if it is needed after the call.
=> Adapt ``jit_var_inc_ref()`` signature

src/op.cpp, src/var.cpp, src/var.h, tests/loop.cpp
When performing scatters within symbolic loops, there is already an implied precondition that writes are non-conflicting across iterations.
So if a user want to call `scatter` multiple times in the loop body the same precondition should be assumed.
=> Scatter: Avoid evaluation within a symbolic scope

src/var.cpp, tests/array.cpp, tests/test.h
Previously, `dr::tile` behaviour wasn't consistent with Python counterpart
```
dr.tile(dr.arange(dr.llvm.UInt32, 3), 3)
[0, 1, 2, 0, 1, 2, 0, 1, 2]
```
```
dr::tile(dr::arange<UInt32>(3), 3))
[0, 0, 0, 1, 1, 1, 2, 2, 2]
```
and seemed to be performing a repeat instead.  Added some small tests as well.
=> Fix `jit_var_tile`. Thanks to @mcrescas

include/drjit-core/jit.h, src/api.cpp, src/registry.cpp, src/registry.h
The PR adds the option to traverse all registry entries for a backend.
This is required for function freezing, as it is not easily possible to get the domains of a variable representing a pointer, when traversing a C++ class such as a scene.
The fix is to just traverse the whole registry.
This PR makes the following changes:
- modifies the `jitc_registry_id_bound` function to return the bound over all domains in the backend if the `domain` argument is a `nullptr`
- Adds a `jitc_registry_fill_ptrs` function, taking a pointer to a memory region to fill with the registered pointers.
- Adds the backend as a field to the `Domain` struct
=> All domain Registry Traversal per Backend

include/drjit-core/jit.h, src/api.cpp, src/call.cpp, src/call.h, src/registry.cpp, src/registry.h, tests/vcall.cpp
In the registry, the `backend` part of the key is replaced by a string-typed `variant`.
See https://github.com/mitsuba-renderer/drjit/pull/313.
=> Call: allow isolation per (variant, domain)

CMakeLists.txt, include/drjit-core/jit.h, src/api.cpp, src/eval.cpp, src/init.cpp, src/internal.h, src/llvm.h, src/llvm_core.cpp, src/record_ts.cpp, src/record_ts.h, src/var.cpp, tests/CMakeLists.txt, tests/record.cpp, tests/test.h, tests/vcall.cpp
This PR implements the Freezing feature in `drjit-core` (depends on  #106).
It makes the following changes:
- Adds the freezing api to `jit.h`, including the following functions: `jit_freeze_start`, `jit_freeze_stop`, `jit_freeze_replay`, `jit_freeze_dry_run`, `jit_freeze_pause`, `jit_freeze_resume`, `jit_freeze_abort` and `jit_freeze_destroy` as well as the `Recording` struct.
- Adds the implementation of the `RecordThreadState`, a wrapper around either the CUDA or LLVM `ThreadState` for freezing them.
=> Frozen ThreadState

src/array.cpp
- On CUDA, the use of `jitc_var_mask_apply(mask_,1)` will attempt to resize the mask to 1 if no other mask is on the thread-state stack which is not what we want
- Instead, let's use the passed in mask size as the argument to `jitc_var_mask_apply`. If the mask on the stack has size 1 or matches the passed-in size then we apply, so this should still be valid
Relevant tests can be found in the Dr.Jit PR [https://github.com/mitsuba-renderer/drjit/pull/321](321)
=> Fix masking for local arrays

include/drjit-core/jit.h, src/op.cpp, tests/mem.cpp, tests/test.h
With a small unit test.
Closes https://github.com/mitsuba-renderer/drjit-core/issues/113.
=> scatter_inc: return correct width even in fully masked case

src/eval.cpp, src/internal.h, src/record_ts.cpp, src/record_ts.h
Commit [0c9c54e](https://github.com/mitsuba-renderer/drjit-core/commit/0c9c54ec5c2963dd576c5a16d10fb2d63d67166f) accidentally introduced a bug, that caused the precomputed hash of a `KernelKey` to no longer be equivalent to the actual hash of that kernel key.
This PR adds the upper 64 bits of the kernel hash to the `KernelKey` struct, memoizing the computation of the hash of the kernel string. The actual hash function is also modified to use this stored hash instead of re-computing the hash of the string.
=> Fixed OptiX kernel hashing bug

src/common.h
For reasons of ABI compatibility, std::mutex uses a legacy locking API on Windows that is significantly slower than std::shared_mutex.
https://stackoverflow.com/questions/69990339/why-is-stdmutex-so-much-worse-than-stdshared-mutex-in-visual-c
=> Use std::shared_mutex in favor of std::mutex on Windows

include/drjit-core/jit.h, src/api.cpp, src/record_ts.cpp, src/registry.cpp, src/registry.h, src/var.cpp, src/var.h, tests/test.h, tests/vcall.cpp
This PR adds various fixes to the `Frozen ThreadState` #107 PR, that appeared after merging.
- Adds logging function for `capture_call_offset` function
- Fix memory leak in `vcall` tests by freeing the copied OptiX SBT and changing `borrow` to `steal` in test
- Adds the ability to traverse the whole registry without a variant string
This PR replaces #115, and changes the source branch.
=> Frozen Functions Fixes

src/optix_api.cpp, src/optix_api.h, src/optix_core.cpp, tests/optix_stubs.cpp, tests/optix_stubs.h, tests/triangle.cpp
This PR contains the minimum set of changes to bump OptiX from version 7.3 to 8.0.
SER and a refactoring of the ray tracing intrinsics will be in another PR.
=> Bump OptiX ABI version to 87 (OptiX 8.0)

src/init.cpp, src/llvm.h, src/llvm_core.cpp, src/llvm_eval.cpp, src/op.cpp
Dr.Jit provides an approximate ``dr.rsqrt()`` operation that performs a reciprocal square root with a very small amount of rounding error (~1 ULP) when compared to the IEEE 754-compliant version. The main benefit is that this has significantly lower latency.
Previously, only the CUDA backend implemented this operation properly, while an IEEE 754-compliant fallback was used on the LLVM backend. This commit adds a proper implementation for AVX, AVX512, and ARM Neon.
=> Properly compile ``rsqrt`` intrinsic on LLVM

include/drjit-core/jit.h, src/init.cpp
There can sometimes be lingering issues in a codebase (e.g., forgotten leftovers from a prior debugging session) that trigger costly CPU<->GPU.
The new ``JitFlag.ForbidSynchronization`` flag will raise an exception in ``jitc_sync_thread()`` to immediately identify such problems.
=> Added ``JitFlag::ForbidSynchronization`` to catch synchronization issues

src/array.cpp
This PR fixes a segfault in the `jitc_array_read` function, where the `variables` vector might be reallocated when calling `jitc_var_mask_apply`. `vo` and `vs` then no longer point to valid memory.
=> Fixed segfault in jitc_array_read

src/array.cpp
Follow-up to https://github.com/mitsuba-renderer/drjit-core/pull/129.
The `jitc_array_write()` function was susceptible to the same issue.
This was caught by running some Mitsuba code with `asan` + DrJit's intense sanitization options.
=> Fix read-after-free in `jitc_array_write()`

include/drjit-core/jit.h, src/var.cpp, tests/basics.cpp
This commit adds a dummy member `VarType::BaseFloat` to the VarType enumeration. This type cannot be used for actual computation.
It is a placeholder to be used in situations where we haven't quite decided what floating point precision to assign to a floating point variable (E.g. a Python scalar float).
This allows us to compute things like `Float16(1.0) + 2.0` without the `2.0` being interpreted as `Float32`, causing an unwanted cast to a higher precision.
=> Added a new `VarType::BaseFloat` for Python type promotion

src/cuda_scatter.cpp
Fixes an issue in the scatter_reduce implementation when using ReduceMode.NoConflicts. The problem was caused by a missing argument in the call to the formatting function (fmt).
Reproducer:
```python
import drjit as dr
from drjit.auto import Int32, UInt32
dr.set_flag(dr.JitFlag.PrintIR, True)
a = Int32([-3, -62, 5])
dr.scatter_add(target=a,
value=Int32([0, 1, 2]), 
index=dr.arange(UInt32, 3), 
mode=dr.ReduceMode.NoConflicts)
print(a)
```
=> CUDA Scatter Reduce NoConflicts - address missing fmt argument

include/drjit-core/jit.h, include/drjit-core/texture.h, src/api.cpp, src/cuda_tex.cpp, src/cuda_tex.h, src/record_ts.cpp
Just a one liner to fix the wrong size being recorded for jitc_var_expand calls.
=> Fix, recording the wrong size for `expand`

src/cuda_api.h
When compiling without dynamic CUDA, we need to include `cudaProfiler.h` for the profiler API to be available.
=> Add missing include when dynamic CUDA is disabled

tests/triangle.cpp
I learned today that C++ value initialization of a struct will only initialize the first union member.
E.g., the following code does not guarantee that all union members are zero:
```cpp
struct A {
...
}
struct B {
...
}
struct C {
union {
A a;
B b;
}
}
...
C c {};
// --> c.b might not be 0 entirely
```
This causes issues when relying on it to zero-initialize complex OptiX API structs (in particular, those with pointer members). I am running Mitsuba & Dr.Jit with a sanitizer that appears to make sure to fill any non-initialized memory with a sequence of non-zero bits to surface those issues. This makes code that relies on this initialization segfault.
This PR fixes these issues in `triangle.cpp`, I will follow up with a PR to fix the same problem in Mitsuba
=> Make sure structs are fully zero initialized

tests/optix_stubs.h
The optix stubs used by the `triangle.cpp` unit tests are outdated and miss a few fields that are used by optix 8.0.
This PR adds the missing fields, replicating the changes already made in Mitsuba: https://github.com/mitsuba-renderer/mitsuba3/pull/1480
Without those changes, the `triangle.cpp` test fails when run under certain sanitizers.
=> Update OptiX API in triangle test to 8.0

include/drjit-core/jit.h, src/cuda_api.cpp, src/cuda_api.h, src/cuda_core.cpp
Patch by @wjakob to help with https://github.com/mitsuba-renderer/mitsuba3/pull/1522.
=> jitc_cuda_sync_stream(): allow sync w.r.t. default per-thread stream

include/drjit-core/half.h
This PR makes `float32_to_float16` and `float16_to_float32` public. This is because they are referred to by Mitsuba's struct converter in some cases: https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/core/struct.cpp#L752
Without these changes, the struct converter cannot be compiled on older instruction sets
=> Make float32 <-> float16 conversions public

src/cuda_eval.cpp, src/internal.h, src/lock.h, src/loop.h
This PR is a fix for symbolic loops when state variables get assigned to other state variables, for example: 
```python
@dr.syntax
def f():
previous, current = ...
while cond(...): # both `previous` and `current` are state variables in this loop
previous = current
current = g(...)
...
```
In symbolic mode, with the CUDA backend, the variable getting assigned an other state variable (`previous` in the example above) would potentially be assigned the new value of the state variable (`g(...)` in the example)  rather than its original value (`current`'s value at the beginning of the loop).
When assembling a `LoopEnd` node in CUDA, for a loop with two state variable `a` and `b`, we'd generate something like this:
```
mov.b32 %inner_in_a, %inner_out_a;
mov.b32 %inner_in_b, %inner_out_b;
bra …
```
=> Fix bug in symbolic CUDA loops

include/drjit-core/jit.h, include/drjit-core/optix.h, src/api.cpp, src/cuda_eval.cpp, src/internal.h, src/optix.h, src/optix_core.cpp, src/trace.h, src/var.cpp, tests/triangle.cpp
This PR adds support for Shader Execution Reordering (SER) in OptiX ray tracing calls (`jit_optix_ray_trace()`). It also adds an explicit reodering function if the user wants to reorder threads based on a key that does not involve any ray intersection information: `jit_optix_reorder`.
The SER functionality can be completely turned off with a new `ShaderExecutionReordering` JIT flag.
No new tests were added. The triangle test was updated to correctly adopt the new ray tracing interface.
=> Shader Execution Reordering

include/drjit-core/array.h, include/drjit-core/jit.h, include/drjit-core/nanostl.h, src/api.cpp, src/init.cpp, src/internal.h, src/lock.h, src/record_ts.cpp, src/record_ts.h, src/util.cpp, src/var.cpp, src/var.h, tests/record.cpp
This PR adds a new function `jit_var_opaque_width`, that constructs an opaque variable, corresponding to the width of another variable. It also notifies the ThreadState, to record and replay this operation.
=> Opaque Width

src/cuda_api.h
Fixes issue #149 by adding the missing symbol to the cuda_api.h
=> Fix build for DRJIT_DYNAMIC_CUDA=OFF

src/record_ts.cpp
This fixes a small issue in record_ts: For literal variables, the `slot` field is undefined. Therefore, we need to make sure to only use `info.slot` if we are not in the case where `type == ParamType::Register`.
The current code likely "works" due to zero initialization of memory, but doesn't work when running with a sanitizer that explicitly does not zero initialize
=> Frozen functions: Avoid invalid memory read for literals

src/llvm_eval.cpp
This PR fixes an issue where a LLVM register could be defined twice when two FP16 operations which depend on eachother required FP32 upcasting, like `dr.minimum()` or `dr.maximum()`. A typical example of this is a call to `dr.clip()`.
=> Fix implicit FP32 casts

include/drjit-core/jit.h, src/cuda_ts.cpp, src/cuda_ts.h, src/eval.cpp, src/internal.h, src/io.h, src/llvm_ts.cpp, src/llvm_ts.h, src/record_ts.cpp, src/record_ts.h
Enables frozen functions to generate kernel history entries, when replaying kernels.
=> Frozen Functions Kernel History

src/record_ts.cpp
This PR fixes a bug, that accidentally left the `use_optix` flag enabled, even though a replayed kernel was not using any optix specific instructions. The underlying thread state then tried to launch an OptiX kernel, without an OptiX pipeline being allocated. This caused segfaults in certain scenarios.
=> Fix Frozen Functions with some OptiX kernels

include/drjit-core/jit.h, src/api.cpp, src/common.h, src/cuda_eval.cpp, src/internal.h, src/llvm_eval.cpp, src/op.cpp, src/op.h, src/var.cpp, tests/basics.cpp
This PR adds a wide (e.g. i32xi32 -> i64) integer multiplication node, which is the central operation underlying the Philox pseudorandom number generator.
Test coverage is added separately at the Dr.Jit level.
=> Add ``jit_var_mul_wide()`` operation for wide integer multiplication

src/var.cpp
Allows communicating that no valid source location is available.
Needed by https://github.com/mitsuba-renderer/drjit/pull/418.
=> `jitc_set_source_location`: special case when no location is available

src/cuda_packet.cpp, src/cuda_packet.h, src/cuda_scatter.cpp, src/llvm_packet.cpp, src/op.cpp
This PR enables us to render a specialized version of the PacketScatter op in CUDA when a reduction operation is specified, with f16 types. It uses the `red.global.add.noftz.f16x2` instruction.
=> Improve packet scatters and gathers

src/malloc.cpp, src/registry.cpp
This patch adds missing checks for `jit_leak_warnings`.
=> Add missing checks for jit_leak_warnings

src/gl_interop.cpp
This fixes compilation errors for the case when `DRJIT_DYNAMIC_CUDA` is off. In that case, we have to be more careful to use the cuda types such as `CUresult` or `CUdeviceptr` where needed.
=> Fix minor typing issues in gl_interop

include/drjit-core/jit.h, src/cuda_eval.cpp
This PR introduces a new JIT flag JitFlag::SpillToSharedMemory to enable spilling of excess registers into shared memory when register pressure is high.
Spilling to shared memory can reduce latency compared to spilling into local memory, potentially improving performance in register-heavy CUDA kernels. The feature is relevant only on backends that support this behavior (e.g., CUDA with PTX ISA 8.7+ and sm_75 or higher).
=> Support for excess register spilling to CUDA shared memory

include/drjit-core/jit.h, src/api.cpp, src/cuda_eval.cpp, src/cuda_scatter.cpp, src/cuda_scatter.h, src/eval.cpp, src/internal.h, src/llvm_eval.cpp, src/llvm_scatter.cpp, src/llvm_scatter.h, src/op.cpp, src/op.h, src/var.cpp, src/var.h
This PR lays the groundwork for implementing `dr.scatter_cas()` and `dr.scatter_exch()`.
The implementation shares a lot of similarities with `scatter_inc`, as the outputs are only valid when used in the same kernel as where the memory write takes place. To do so, it also relies on the `consumed` field of `Variables`.
PTX has instructions to peform both of these operations trivially, where as the LLVM implementation must rely on a loop over the vectorization width; there currently is no `cmpxchg` or ` atomicrmw` for vectorized types in the LLVM IR spec.
As always, tests are contained in the Dr.Jit PR: https://github.com/mitsuba-renderer/drjit/pull/450
=> New JIT nodes for `dr.scatter_cas()` and `dr.scatter_exch()`
